name: movies_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.0
  provider: ^6.0.5
  firebase_core: ^2.16.0
  shared_preferences: ^2.2.1
  http:
  youtube_player_flutter: ^8.1.2
  sqflite: ^2.3.0
  path: ^1.8.3
  readmore: ^2.2.0
  google_sign_in: ^6.1.5
  email_auth: ^1.1.1





dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.3

flutter_native_splash:
  image: assets/images/img_1.png
  color: "#ffffff"
  android: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/img1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/img1.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:


  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Apple
      fonts:
        - asset: assets/fonts/Tangerine-Bold.ttf
          weight: 900
    - family: Inter
      fonts:
       - asset: assets/fonts/Inter-Regular.ttf
         weight: 600

